;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░│
;; │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░|
;; └────────────────────────────────────────────────────────────┘

[bar/primera]
monitor = eDP
width = 100%
height = 26
border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin = 1

line-size = 3
line-color = ${colors.red}

background = ${colors.fondo}

; FONTS DE POLYBAR /////////////////////////////////////////////////////////////
font-0 = "Noto Sans:size=9;3"
font-1 = "Iosevka Nerd Font:size=10;2"
font-2 = "Iosevka Nerd Font:size=10;2"

; MODULOS DE POLYBAR ///////////////////////////////////////////////////////////
modules-left = sep2 menu sep bspwm sep term web files sep xwindow
modules-center =  date
modules-right = xkeyboard sep memory cpu sep systray pulseaudio bluetooth network sep battery notificaciones sep sysmenu sep2

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[settings]
screenchange-reload = false
pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[colors]
black = ${xrdb:color0:#1d2021}
darkred = ${xrdb:color1:#cc241d}
darkgreen = ${xrdb:color2:#98971a}
darkyellow = ${xrdb:color3:#d79921}
darkblue = ${xrdb:color4:#458588}
darkmagenta = ${xrdb:color5:#b16286}
darkcyan = ${xrdb:color6:#689d6a}
lightgray = ${xrdb:color7:#a89984}
gray = ${xrdb:color8:#928374}
red = ${xrdb:color9:#fb4934}
green = ${xrdb:color10:#b8bb26}
yellow = ${xrdb:color11:#fabd2f}
blue = ${xrdb:color12:#83a598}
magenta = ${xrdb:color13:#d3869b}
cyan = ${xrdb:color14:#8ec07c}
white = ${xrdb:color15:#ffffff}
background = ${xrdb:color256:#dd1d2021}
foreground = ${xrdb:color257:#ebdbb2}
fondo = ${xrdb:colors22:#2E3440}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery
battery = BAT1
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-charging = %percentage%%
label-discharging = %percentage%%

label-full =   %percentage%%
label-full-foreground = #a3be8c

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-charging-foreground = #ebcb8b

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-0-foreground = #bf616a
ramp-capacity-foreground = #d8dee9

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock

format = <label-layout>
format-prefix = "󰌌 "
format-prefix-foreground = ${colors.white}

label-layout = %layout%
label-layout-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

; --- LA LÍNEA CLAVE ---
; Asegúrate de que <ramp-volume> esté ANTES de <label-volume>
format-volume = <ramp-volume>
format-volume-padding = 2
format-volume-foreground = ${colors.white}

; El texto del porcentaje
;label-volume = %percentage%%

; Iconos obligatorios para que <ramp-volume> funcione con Iosevka
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 

; --- CONFIGURACIÓN MUTE ---
format-muted = <label-muted>
format-muted-padding = 2
; Aquí también añadimos el icono de silencio antes del porcentaje
label-muted = 
label-muted-foreground = ${colors.white}

click-right = pavucontrol

[module/date]
type = internal/date
interval = 1.0
time = %d de %B %I:%M %p
format = <label>
format-padding = 2
label = %time%

[module/notificaciones]
type = custom/text
; Icono de campana con alerta compatible con Iosevka
content = ""
content-padding = 2
; Reactivado: Usando el color yellow de tu paleta
content-foreground = ${colors.white}

;click-left = dunstctl history-pop
click-right = dunstctl close-all

[module/network]
type = internal/network
interface = wlan0
interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-padding = 2
format-disconnected = <label-disconnected>
format-disconnected-padding = 2

label-connected = "%{A1:networkmanager_dmenu &:}說%{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:}ﲁ%{A}"

[module/menu]
type = custom/text
content = 
content-background = ${colors.fondo}
content-foreground = ${colors.red}
content-padding = 1
click-left = ~/.config/rofi/scripts/launcher.sh 
click-right = ~/.config/rofi/scripts/launcher.sh

[module/sysmenu]
type = custom/text
content = 
content-padding = 1
click-left = ~/.config/rofi/powermenu/type-1/powermenu.sh

[module/sep]
type = custom/text
content = |
content-padding = 1

[module/sep2]
type = custom/text
content = |
content-foreground = ${colors.fondo}
content-background = ${colors.fondo}
content-padding = 0.5

[module/term]
type = custom/text
content = "%{T3}>_%{T-}"
content-padding = 2
click-left  = kitty &

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " CPU "
label = %percentage:2%%

[module/web]
type = custom/text
content = "%{T3}%{T-}"
content-padding = 2
click-left  = firefox &

[module/files]
type = custom/text
content = "%{T3}%{T-}"
content-padding = 2
click-left  = thunar &

[module/xwindow]
type = internal/xwindow
label = %title%

[module/bspwm]
type = internal/bspwm
label-monitor = %name%
pin-workspaces = true

label-focused = %name%
label-focused-foreground = ${colors.black}
label-focused-background = ${colors.blue}
label-focused-underline= ${colors.blue}
label-focused-padding = 3

label-occupied = %name%
label-occupied-underline = ${colors.yellow}
label-occupied-padding = 3

label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 3
label-empty = %name%
label-empty-padding = 3


[module/bluetooth]
type = custom/text

; Icono de Bluetooth de Nerd Fonts
content = "  "
content-padding = 1
; Usamos el color 'blue' de tu sección [colors]
content-foreground = ${colors.white}

; Al hacer click izquierdo abre el gestor para conectar audífonos o mandos
click-left = blueman-manager &

; Al hacer click derecho puedes encender/apagar rápidamente el Bluetooth
click-right = rfkill toggle bluetooth

[module/systray]
type = internal/tray

; Tamaño de los iconos (ajustado para tu barra de altura 26)
tray-size = 65%

; Espaciado entre los iconos de la bandeja
tray-spacing = 8pt

; Margen a los lados del módulo completo
format-margin = 8pt

; Esto es importante para bspwm
tray-background = ${colors.fondo}
